const types = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	SET_AUTH_USER: "SET_AUTH_USER",
	REMOVE_AUTH_USER: "REMOVE_AUTH_USER",
	LOGIN_FAIL: "LOGIN_FAIL",
	LOAD_USER: "LOAD_USER"
};

export default types;
